name: Test Action

on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send ding
        uses: ./
        with:
          access_token: ${{secrets.ACCESS_TOKEN}}
          title: 'title'
          content: |
            ## subtitle
            ### content
